{{- if .Values.kernelModule.enabled }}
{{- if .Values.kernelModule.firmware.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kernelModule.firmware.configMapName | default "mock-accel-firmware" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mock-device.labels" . | nindent 4 }}
binaryData:
  mock-accel-wordlist.txt: |-
{{ .Files.Get "firmware/mock-accel-wordlist.txt" | b64enc | indent 4 }}
{{- end }}
{{- end }}
